// <auto-generated />
using System;
using CooperativeFinancing.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CooperativeFinancing.Migrations
{
    [DbContext(typeof(CooperativeContext))]
    [Migration("20250303003554_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CooperativeFinancing.Models.CooperativeLoans", b =>
                {
                    b.Property<int>("Loan_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Loan_Id"));

                    b.Property<float>("Annual_Interest")
                        .HasColumnType("float");

                    b.Property<DateTime>("End_Month")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("First_Month")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Loan_Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Member_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Monthly_Payment")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Purpose_Loan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Release_Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Payment")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Loan_Id");

                    b.ToTable("CooperativeLoans");

                    b.HasData(
                        new
                        {
                            Loan_Id = 1,
                            Annual_Interest = 5.5f,
                            End_Month = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            First_Month = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Loan_Amount = 5000.00m,
                            Member_Id = 1,
                            Monthly_Payment = 230.00m,
                            Purpose_Loan = "Business Expansion",
                            Release_Date = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Term = 24,
                            Total_Payment = 5520.00m
                        },
                        new
                        {
                            Loan_Id = 2,
                            Annual_Interest = 6.2f,
                            End_Month = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            First_Month = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Loan_Amount = 7000.00m,
                            Member_Id = 2,
                            Monthly_Payment = 215.00m,
                            Purpose_Loan = "Home Renovation",
                            Release_Date = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Term = 36,
                            Total_Payment = 7740.00m
                        });
                });

            modelBuilder.Entity("CooperativeFinancing.Models.CooperativeMembers", b =>
                {
                    b.Property<int>("Member_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Member_Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("Contribution")
                        .HasMaxLength(45)
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Member_Id");

                    b.ToTable("CooperativeMembers");

                    b.HasData(
                        new
                        {
                            Member_Id = 1,
                            City = "Springfield",
                            Contribution = 600,
                            Email = "john.doe@example.com",
                            First_Name = "John",
                            JoinDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Last_Name = "Doe",
                            Phone = "123-456-7890",
                            Province = "Illinois",
                            Street = "123 Elm St"
                        },
                        new
                        {
                            Member_Id = 2,
                            City = "Los Angeles",
                            Contribution = 500,
                            Email = "jane.smith@example.com",
                            First_Name = "Jane",
                            JoinDate = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Last_Name = "Smith",
                            Phone = "987-654-3210",
                            Province = "California",
                            Street = "456 Oak Ave"
                        });
                });

            modelBuilder.Entity("CooperativeFinancing.Models.CooperativePayment", b =>
                {
                    b.Property<int>("Payment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Payment_Id"));

                    b.Property<int>("Loan_Id")
                        .HasColumnType("int");

                    b.Property<int>("Member_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Payment_Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Payment_Date")
                        .HasColumnType("date");

                    b.HasKey("Payment_Id");

                    b.ToTable("CooperativePayment");

                    b.HasData(
                        new
                        {
                            Payment_Id = 1,
                            Loan_Id = 1,
                            Member_Id = 1,
                            Payment_Amount = 500.00m,
                            Payment_Date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Payment_Id = 2,
                            Loan_Id = 1,
                            Member_Id = 1,
                            Payment_Amount = 500.00m,
                            Payment_Date = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Payment_Id = 3,
                            Loan_Id = 2,
                            Member_Id = 2,
                            Payment_Amount = 700.00m,
                            Payment_Date = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CooperativeFinancing.Models.CooperativeUsers", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<bool>("Is_Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Member_Id")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("User_Id");

                    b.ToTable("CooperativeUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
